### ISSUE TITLE
Selenium not working in the right way?

### ISSUE THREAD

**Issue by SonoAX** [Shifty-The-Dev/RedditVideoGenerator#13]
Before anyone says anything, im very new in python and linux, and I don't know how it should work. It gives me this error so, can someone help me? It seems to be related to some firefox driver but I'm not sure.

```
Exception ignored on calling ctypes callback function: <bound method EspeakDriver._onSynth of <pyttsx3.drivers.espeak.EspeakDriver object at 0x7ff4bcc15c30>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/pyttsx3/drivers/espeak.py", line 171, in _onSynth
    self._proxy.notify('finished-utterance', completed=True)
ReferenceError: weakly-referenced object no longer exists
Taking screenshots...
Traceback (most recent call last):
  File "/tmp/RedditVideoGenerator/main.py", line 87, in <module>
    createVideo()
  File "/tmp/RedditVideoGenerator/main.py", line 21, in createVideo
    screenshot.getPostScreenshots(fileName, script)
  File "/tmp/RedditVideoGenerator/screenshot.py", line 13, in getPostScreenshots
    driver, wait = __setupDriver(script.url)
  File "/tmp/RedditVideoGenerator/screenshot.py", line 34, in __setupDriver
    driver = webdriver.Firefox(options=options)
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/firefox/webdriver.py", line 199, in __init__
    super().__init__(command_executor=executor, options=options, keep_alive=True)
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/remote/webdriver.py", line 286, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/remote/webdriver.py", line 378, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/remote/webdriver.py", line 440, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/remote/errorhandler.py", line 245, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: Process unexpectedly closed with status 1
```

**Comment by SonoAX** [comment]
Now it says this: 
```
Traceback (most recent call last):
  File "/tmp/RedditVideoGenerator/main.py", line 87, in <module>
    createVideo()
  File "/tmp/RedditVideoGenerator/main.py", line 21, in createVideo
    screenshot.getPostScreenshots(fileName, script)
  File "/tmp/RedditVideoGenerator/screenshot.py", line 13, in getPostScreenshots
    driver, wait = __setupDriver(script.url)
  File "/tmp/RedditVideoGenerator/screenshot.py", line 34, in __setupDriver
    driver = webdriver.Firefox(options=options)
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/firefox/webdriver.py", line 164, in __init__
    self.service.start()
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/common/service.py", line 81, in start
    raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: 'geckodriver' executable needs to be in PATH.
```

**Comment by biffotmc** [comment]
you need geckodriver, theres many tutorials/downloads online

**Comment by SonoAX** [comment]
Can you tell me in a short way how to quickly install it? Thx

**Comment by SonoAX** [comment]
Update, i followed this guide (in italian) and it now gives me this error: Guide: 

# Scarica l'ultima versione del geckodriver per Linux
wget -O geckodriver.tar.gz "https://github.com/mozilla/geckodriver/releases/latest/download/geckodriver-linux64.tar.gz"

# Estrai il file
tar -xvzf geckodriver.tar.gz

# Sposta il file nella directory /usr/local/bin
sudo mv geckodriver /usr/local/bin/

# Imposta i permessi
sudo chmod +x /usr/local/bin/geckodriver


# Error
```
Exception ignored on calling ctypes callback function: <bound method EspeakDriver._onSynth of <pyttsx3.drivers.espeak.EspeakDriver object at 0x7f0d93ce96f0>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/pyttsx3/drivers/espeak.py", line 171, in _onSynth
    self._proxy.notify('finished-utterance', completed=True)
ReferenceError: weakly-referenced object no longer exists
Taking screenshots...
Traceback (most recent call last):
  File "/tmp/RedditVideoGenerator/main.py", line 87, in <module>
    createVideo()
  File "/tmp/RedditVideoGenerator/main.py", line 21, in createVideo
    screenshot.getPostScreenshots(fileName, script)
  File "/tmp/RedditVideoGenerator/screenshot.py", line 13, in getPostScreenshots
    driver, wait = __setupDriver(script.url)
  File "/tmp/RedditVideoGenerator/screenshot.py", line 34, in __setupDriver
    driver = webdriver.Firefox(options=options)
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/firefox/webdriver.py", line 170, in __init__
    RemoteWebDriver.__init__(
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.10/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: Process unexpectedly closed with status 1

```

**Comment by biffotmc** [comment]
sorry i've only used it on windows

**Comment by SonoAX** [comment]
can you tell me how you have done it. I tried but i kept running into problems. Thx

**Comment by biffotmc** [comment]
on windows?

**Comment by SonoAX** [comment]
yes
