### ISSUE TITLE
Can u help me with the code?

### ISSUE THREAD

**Issue by I0633852860** [Shifty-The-Dev/RedditVideoGenerator#14]
[0] How is everyone feeling about Donald Trump officially being under arrest ?     9776    4.5 hours ago
[1] Citizens of NATO aligned countries. How do you feel now that Finland has officially joined the alliance?     1042    5.3 hours ago
[2] What is your IRL superpower?     578    23.0 hours ago
[3] What is 100% worth the money?     527    24.1 hours ago
Input :1
Exception ignored on calling ctypes callback function: <bound method EspeakDriver._onSynth of <pyttsx3.drivers.espeak.EspeakDriver object at 0x7a02bc3f6ee0>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/pyttsx3/drivers/espeak.py", line 171, in _onSynth
    self._proxy.notify('finished-utterance', completed=True)
ReferenceError: weakly-referenced object no longer exists
Creating video for post: Citizens of NATO aligned countries. How do you feel now that Finland has officially joined the alliance?
Url: https://www.reddit.com/r/AskReddit/comments/12bpnl6/citizens_of_nato_aligned_countries_how_do_you/
Traceback (most recent call last):
  File "/home/yevgen/RedditVideoGenerator/main.py", line 87, in <module>
    createVideo()
  File "/home/yevgen/RedditVideoGenerator/main.py", line 17, in createVideo
    script = reddit.getContent(outputDir, postOptionCount)
  File "/home/yevgen/RedditVideoGenerator/reddit.py", line 28, in getContent
    return __getContentFromPost(selectedPost)
  File "/home/yevgen/RedditVideoGenerator/reddit.py", line 62, in __getContentFromPost
    if(content.addCommentScene(markdown_to_text.markdown_to_text(comment.body), comment.id)):
  File "/home/yevgen/RedditVideoGenerator/videoscript.py", line 35, in addCommentScene
    frame.audioClip = self.__createVoiceOver(commentId, text)
  File "/home/yevgen/RedditVideoGenerator/videoscript.py", line 48, in __createVoiceOver
    audioClip = AudioFileClip(file_path)
  File "/usr/local/lib/python3.9/dist-packages/moviepy/audio/io/AudioFileClip.py", line 70, in __init__
    self.reader = FFMPEG_AudioReader(filename, fps=fps, nbytes=nbytes,
  File "/usr/local/lib/python3.9/dist-packages/moviepy/audio/io/readers.py", line 51, in __init__
    infos = ffmpeg_parse_infos(filename)
  File "/usr/local/lib/python3.9/dist-packages/moviepy/video/io/ffmpeg_reader.py", line 270, in ffmpeg_parse_infos
    raise IOError(("MoviePy error: the file %s could not be found!\n"
OSError: MoviePy error: the file Voiceovers/2023-04-05-12bpnl6-jexwbq5.mp3 could not be found!
Please check that you entered the correct path.

**Comment by I0633852860** [comment]
python3 main.py 
[0] How is everyone feeling about Donald Trump officially being under arrest ?     13364    5.5 hours ago
[1] Citizens of NATO aligned countries. How do you feel now that Finland has officially joined the alliance?     1427    6.3 hours ago
[2] What is your IRL superpower?     585    23.9 hours ago
[3] To the people who creep forward several times while waiting at a red light, why?     333    7.9 hours ago
Input :0
Traceback (most recent call last):
  File "/RedditVideoGenerator/main.py", line 87, in <module>
    createVideo()
  File "/RedditVideoGenerator/main.py", line 17, in createVideo
    script = reddit.getContent(outputDir, postOptionCount)
  File "/RedditVideoGenerator/reddit.py", line 28, in getContent
    return __getContentFromPost(selectedPost)
  File "/RedditVideoGenerator/reddit.py", line 56, in __getContentFromPost
    content = VideoScript(submission.url, submission.title, submission.id)
  File "/RedditVideoGenerator/videoscript.py", line 22, in __init__
    self.titleAudioClip = self.__createVoiceOver("title", title)
  File "/RedditVideoGenerator/videoscript.py", line 48, in __createVoiceOver
    audioClip = AudioFileClip(file_path)
  File "/home/yevgen/.local/lib/python3.9/site-packages/moviepy/audio/io/AudioFileClip.py", line 70, in __init__
    self.reader = FFMPEG_AudioReader(filename, fps=fps, nbytes=nbytes,
  File "/home/yevgen/.local/lib/python3.9/site-packages/moviepy/audio/io/readers.py", line 51, in __init__
    infos = ffmpeg_parse_infos(filename)
  File "/home/yevgen/.local/lib/python3.9/site-packages/moviepy/video/io/ffmpeg_reader.py", line 270, in ffmpeg_parse_infos
    raise IOError(("MoviePy error: the file %s could not be found!\n"
OSError: MoviePy error: the file Voiceovers/2023-04-05-12br1id-title.mp3 could not be found!
Please check that you entered the correct path.

**Comment by rborsetti** [comment]
The error thrown is: "OSError: MoviePy error: the file Voiceovers/2023-04-05-12br1id-title.mp3 could not be found!
Please check that you entered the correct path." Without more access to your system, it's hard to debug what has occurred.

**Comment by kalix123** [comment]
Same issue here. I'm on Linux. The audio files will generate but I still get a similar error.

```
Input :0
Creating video for post: What was discontinued, but you miss like hell and you wish came back?
Url: https://www.reddit.com/r/AskReddit/comments/12cmf8s/what_was_discontinued_but_you_miss_like_hell_and/
Traceback (most recent call last):
  File "/home/neptune/.local/lib/python3.8/site-packages/moviepy/video/io/ffmpeg_reader.py", line 285, in ffmpeg_parse_infos
    line = [l for l in lines if keyword in l][index]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last): 
 File "main.py", line 89, in <module>
    createVideo()
  File "main.py", line 17, in createVideo
    script = reddit.getContent(outputDir, postOptionCount)
  File "/home/neptune/Projects/CodeProjects/video_maker/reddit.py", line 28, in getContent
    return __getContentFromPost(selectedPost)
  File "/home/neptune/Projects/CodeProjects/video_maker/reddit.py", line 62, in __getContentFromPost
    if(content.addCommentScene(markdown_to_text.markdown_to_text(comment.body), comment.id)):
  File "/home/neptune/Projects/CodeProjects/video_maker/videoscript.py", line 35, in addCommentScene
    frame.audioClip = self.__createVoiceOver(commentId, text)
  File "/home/neptune/Projects/CodeProjects/video_maker/videoscript.py", line 48, in __createVoiceOver
    audioClip = AudioFileClip(file_path)
  File "/home/neptune/.local/lib/python3.8/site-packages/moviepy/audio/io/AudioFileClip.py", line 70, in __init__
    self.reader = FFMPEG_AudioReader(filename, fps=fps, nbytes=nbytes,
  File "/home/neptune/.local/lib/python3.8/site-packages/moviepy/audio/io/readers.py", line 51, in __init__
    infos = ffmpeg_parse_infos(filename)
  File "/home/neptune/.local/lib/python3.8/site-packages/moviepy/video/io/ffmpeg_reader.py", line 289, in ffmpeg_parse_infos
    raise IOError(("MoviePy error: failed to read the duration of file %s.\n"
OSError: MoviePy error: failed to read the duration of file /home/neptune/Projects/CodeProjects/video_maker/Voiceovers/2023-04-06-12cmf8s-jf3a9m7.mp3.
Here are the file infos returned by ffmpeg:

ffmpeg version 4.2.2-static https://johnvansickle.com/ffmpeg/  Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 8 (Debian 8.3.0-6)
  configuration: --enable-gpl --enable-version3 --enable-static --disable-debug --disable-ffplay --disable-indev=sndio --disable-outdev=sndio --cc=gcc --enable-fontconfig --enable-frei0r --enable-gnutls --enable-gmp --enable-libgme
--enable-gray --enable-libaom --enable-libfribidi --enable-libass --enable-libvmaf --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-librubberband --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libvorbis --enable-libopus --enable-libtheora --enable-libvidstab
--enable-libvo-amrwbenc --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libdav1d --enable-libxvid --enable-libzvbi --enable-libzimg
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100
[mp3 @ 0x669b340] Format mp3 detected only with low score of 1, misdetection possible!
[mp3 @ 0x669b340] Failed to read frame size: Could not seek to 1026.
/home/neptune/Projects/CodeProjects/video_maker/Voiceovers/2023-04-06-12cmf8s-jf3a9m7.mp3: Invalid argument

```

**Comment by rborsetti** [comment]
Looking into it further... the line engine.save_to_file(text, filePath) in voiceover.py appears to be the issue. No matter what I change, it just doesn't save the voiceover to a file...

**Comment by ItsLeon15** [comment]
@rborsetti You can change it to something like this. It's only a workaround and is by all means not a permanent solution to the error.

```python
import pyttsx3

def create_voice_over(fileName, text):
    filePath = f"E:/Voiceovers/{fileName}.mp3"
    engine = pyttsx3.init()
    engine.save_to_file(text, filePath)
    engine.runAndWait()
    return filePath
```

**Comment by kariuki-kithinji** [comment]
checkout my fork , I use a completely different text to speech engine , better sounding and it doesn't have these issues
