### ISSUE TITLE
Selenium TimeoutException when getting screenshots

### ISSUE THREAD

**Issue by Dr0mus** [Shifty-The-Dev/RedditVideoGenerator#19]
```
Traceback (most recent call last):
  File "C:\Users\Dromu\Documents\code\RedditVideoGenerator\main.py", line 89, in <module>
    createVideo()
  File "C:\Users\Dromu\Documents\code\RedditVideoGenerator\main.py", line 21, in createVideo
    screenshot.getPostScreenshots(fileName, script)
  File "C:\Users\Dromu\Documents\code\RedditVideoGenerator\screenshot.py", line 15, in getPostScreenshots
    script.titleSCFile = __takeScreenshot(filePrefix, driver, wait)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dromu\Documents\code\RedditVideoGenerator\screenshot.py", line 22, in __takeScreenshot
    search = wait.until(EC.presence_of_element_located((method, handle)))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Dromu\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\selenium\webdriver\support\wait.py", line 95, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:
Stacktrace:
RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8
WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:180:5
NoSuchElementError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:392:5
element.find/</<@chrome://remote/content/marionette/element.sys.mjs:134:16
```
I am getting this exception when selenium tries to get screenshots. I tried to run it multiple times but it all got the same thing. One thing that appeared when I tried it was the google login message: 
![image](https://user-images.githubusercontent.com/38384816/231301703-70256e53-c561-48b6-b503-6455f55e1107.png)
aside from that I don't know what else can cause it. I just ran it and it just keeps appearing.

**Comment by ghost** [comment]
same
